services:
  app:
    image: todo-frontend-dev
    volumes:
      - ./todo-frontend/:/usr/src/app

  server:
    image: todo-backend-dev
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

  mongo:
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: mongo

  redis:
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: redis

volumes:
  mongo_data:
  redis_data:
