services:
  app:
    image: blog-front-dev
    build:
      context: ./blog-front
      dockerfile: dev.Dockerfile
    environment:
      REACT_APP_BACKEND_URI: ${REACT_APP_BACKEND_URI}
    volumes:
      - ./blog-front/:/usr/src/app
    container_name: blog-front-dev

  server:
    image: blog-back-dev
    build:
      context: ./blog-back
      dockerfile: dev.Dockerfile
    environment:
      MONGODB_URI: ${MONGODB_URI}
      SECRET: ${SECRET}
    volumes:
      - ./blog-back/:/usr/src/app
    container_name: blog-back-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-blog-dev
    depends_on:
      - app
      - server
